# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: 
         name: "Deploy Aplicacion 1"
         command: |
            cd ./aplicacion1
            yarn install
      - run: 
         name: "Deploy Aplicacion 2"
         command: |
            cd ./aplicacion2
            yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: 
         name: "Deploy Aplicacion 1"
         command: |
            cd ./aplicacion1
            yarn run test
      - run: 
         name: "Deploy Aplicacion 2"
         command: |
            cd ./aplicacion2
            yarn run test
  deployDevelopment:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - add_ssh_keys:
          fingerprints:
            - "a6:92:78:56:74:59:3b:f3:7f:a7:69:ed:7f:99:af:29"
      - run: 
         name: "Deploy Aplicacion 1"
         command: |
            cd ./aplicacion1
            yarn run build
            ssh -o StrictHostKeyChecking=no ubuntu@3.223.125.157 "mkdir -p App1"
            scp -o StrictHostKeyChecking=no -r ./build/* ubuntu@3.223.125.157:~/App1
      - run: 
         name: "Deploy Aplicacion 2"
         command: |
            cd ./aplicacion2
            yarn run build
            ssh -o StrictHostKeyChecking=no ubuntu@3.223.125.157 "mkdir -p App2"
            scp -o StrictHostKeyChecking=no -r ./build/* ubuntu@3.223.125.157:~/App2
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  productionDeploy:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - add_ssh_keys:
          fingerprints:
            - "f4:1c:cf:8e:31:a2:93:4a:4a:6d:58:18:f9:5c:19:64"
      - run: 
         name: "Deploy Aplicacion 1"
         command: |
            cd ./aplicacion1
            yarn run build
            ssh -o StrictHostKeyChecking=no ubuntu@34.201.47.241 "mkdir -p App1"
            scp -o StrictHostKeyChecking=no -r ./build/* ubuntu@34.201.47.241:~/App1
      - run: 
         name: "Deploy Aplicacion 2"
         command: |
            cd ./aplicacion2
            yarn run build
            ssh -o StrictHostKeyChecking=no ubuntu@34.201.47.241 "mkdir -p App2"
            scp -o StrictHostKeyChecking=no -r ./build/* ubuntu@34.201.47.241:~/App2
      
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

 
    


workflows:
  version: 2
  normal_run:
    jobs:
      - build: 
          filters:
            branches:
              only:
                - master
      - test:
          requires:
            - build
          filters:
            branches:
              only:
                - master
      - deployDevelopment:
          requires:
            - build
            - test
          filters:
            branches:
              only:
                - master
      - request-testing:
          type: approval
          requires:
            - deployDevelopment
            - test
      - productionDeploy:
          requires:
            - request-testing
          filters:
            branches:
              only:
                - master  
